# Generated by Django 6.0.4 on 2026-04-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('reopened', 'Переоткрыта')], default='created', max_length=20)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_from', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_to', models.CharField(max_length=50)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='task_manager.task')),
            ],
        ),
    ]
